wowserhq/wowser

- .gitignore
- README.md
- src/scripts/lib/server/index.js
- src/scripts/lib/server/pipeline/index.js
- src/scripts/lib/server/utils/server-config/index.js
- src/scripts/lib/server/utils/server-config/setup-prompts.js
> Startup instructions updated, removed references to data folder

- src/lib/realms/handler.js
This corrects the REALM_LIST packet structure to include an unknown uint32 after the opcode. With the change, the packet should better match retail, and makes it possible to retrieve a realm list from TrinityCore's authserver.
> Fixed REALM_LIST packet structure.

- src/lib/pipeline/m2/submesh.js
- src/lib/pipeline/wmo/index.js
I've implemented blending modes 5 and 6 for M2s, so that should be the full extend of blending modes involved with M2s. I haven't had a chance to find M2s that utilize anything beyond blending modes 0, 1, and 2, so there's a chance I have a few flaws in my implementation.
I've also added transparent rendering support to WMOs. I hope I put the logic in a reasonable place.
> More transparency / blending improvements

- src/components/game/index.jsx
- src/lib/game/world/handler.js
- src/lib/game/world/map.js
- src/lib/pipeline/m2/index.js
- src/lib/pipeline/m2/submesh.js
Bones that have the billboard flag set (0x08) now face the camera and update to continue facing the camera when the camera rotates. This is done with a few hooks in to the animate() handler in ```game\index.jsx``` -- not sure if that's the best approach, but it hopefully does the trick for now.
In addition to the billboard support, I've fixed up some issues with render flags. In particular: any submesh that is billboarded now has two sided rendering on the material to avoid vanishing textures when moving / rotating about the world; alpha transparencies should now apply to textures in any billboarded submesh; and the options for one of the blending modes have been corrected to proper values.
A side note about transparency flagging for materials: at some point, this is going to have to be …
> M2 bone billboarding support

- src/components/game/index.jsx
- src/lib/game/unit.js
- src/lib/game/world/handler.js
- src/lib/game/world/map.js
- src/lib/pipeline/m2/animation-manager.js
- src/lib/pipeline/m2/index.js
- src/lib/pipeline/m2/submesh.js
* When M2s are loaded, their bone animations (translation, rotation, and scaling) are also loaded using AnimationManager, a simple wrapper around the three.js animation system. Additionally, transparency animations on M2 submesh textures are registered with the parent M2's AnimationManager.
* The first-by-index animation in each loaded unit and doodad M2 is auto-played on infinite loop.
* Added use of texture lookup table indirection when selecting textures for M2 skins' texture units. This fixes textures on several M2s, including the gryphon roosts and wells in Darkshire.
* Multiple texture units are applied in order using aligned child meshes on the submesh group. A more appropriate solution would likely involve blending multiple textures using a shader.
* Added missing blending …
> Initial M2 animation support and improved M2 texture handling

- src/lib/pipeline/m2/index.js
- src/lib/pipeline/m2/submesh.js
**Replaced several forEach loops with faster for loops**
```forEach``` is quite a bit slower in Chrome than a traditional ```for``` loop. Until Chrome better optimizes ```forEach```, we probably want to avoid it in any code path that executes frequently.
Interestingly, ```forEach``` seems to be fairly comparable to ```for``` on Firefox.
**Simplified translation value transform**
Turns out it's not necessary to incur the expense of cloning the bone to translate it. Rather, simply cloning the bone's position and calling ```add()``` on it with the translation vector gets the job done.
> M2: Basic performance improvements

- src/lib/server/pipeline/index.js
After the pipeline server responds to a request, there's no call to ```close()``` on ```req.resource```, which is a ```File``` from ```blizzardry/src/lib/mpq/file.js```.
I believe ```close()``` is necessary to get StormLib to free up its handle on the file loaded out of the MPQ.
> Pipeline: Fix resource leak

- src/lib/server/index.js
The pipeline server now spawns a number of worker processes matching the CPU count in the host, capped at a max of 4. This reduces the chance that slow-to-complete requests to the pipeline server block other requests from being fulfilled.
> Pipeline: Concurrency

- src/lib/game/world/map.js
- src/lib/pipeline/m2/index.js
- src/lib/pipeline/m2/material/index.js
- src/lib/pipeline/m2/material/shader.frag
- src/lib/pipeline/m2/material/shader.vert
- src/lib/pipeline/m2/submesh.js
* M2s no longer overuse ```THREE.SkinnedMesh``` and skinned materials. M2s without bone animations now create regular ```THREE.Mesh``` objects, which do not incur as much cost in the render loop.
* Texture units (which represent render passes in the actual World of Warcraft client) are now given separate materials, 1:1 with the number of units. When submeshes are created for an M2, all applicable texture units are turned into child ```SkinnedMesh``` (or, if not animated, vanilla ```Mesh```) objects, with the aforementioned material attached. As best I can tell, this should ensure proper drawing order between units.
* M2 materials are now full blown ```ShaderMaterial```s.
* Initial work on blending together multiple textures within individual texture units. Currently, only a few shader …
> M2: Refactor

- webpack.config.js
It appears that ```webpack``` was hunting for ```json-loader``` in the Blizzardry directory, instead of in the Wowser directory. This may only be an issue with ```npm >= 3``` (it impacted me, and I'm on ```3.3.12```)
> Fixed incorrect node_module path assumption made by webpack

- src/components/game/index.jsx
- src/components/game/stats/index.jsx
- src/components/game/stats/index.styl
- src/lib/game/unit.js
- src/lib/game/world/doodad-manager.js
- src/lib/game/world/handler.js
- src/lib/game/world/map.js
- src/lib/game/world/terrain-manager.js
- src/lib/game/world/wmo-manager.js
- src/lib/pipeline/adt/chunk/index.js
- src/lib/pipeline/adt/chunk/material.js
- src/lib/pipeline/m2/animation-manager.js
- src/lib/pipeline/m2/blueprint.js
- src/lib/pipeline/m2/index.js
- src/lib/pipeline/m2/material/index.js
- src/lib/pipeline/m2/submesh.js
- src/lib/pipeline/texture-loader.js
- src/lib/pipeline/wmo/blueprint.js
- src/lib/pipeline/wmo/group/blueprint.js
- src/lib/pipeline/wmo/group/index.js
- src/lib/pipeline/wmo/index.js
- src/lib/pipeline/wmo/material/index.js
* Terrain, doodad, and WMO managers are now used to gracefully add and remove map chunk content to and from the map.
* Rather than attempting to load everything as fast as possible (the current behavior), smaller portions of doodads, WMOs, WMO groups, and WMO doodads are loaded via the managers at configurable intervals. The same holds true for unloading.
* WMO groups are loaded outdoor-first, to minimize the chance for visible pop-in when approaching large WMOs such as capital cities.
* When map doodads and WMOs are no longer referenced by the set of loaded map chunks, they are removed from the map. Large WMOs are unloaded on a timed delay, to prevent excessive loading and unloading when chunk boundaries are crossed.
* WMO doodads are now added to their relevant WMO group, and being to …
> Feature: Map managers

- src/lib/pipeline/adt/chunk/material.js
Texture array uniforms need to contain at least one value or WebGL
prevents loading the uniform and emits an error. ADT chunk alpha maps,
in some cases, may have zero values (such as when the terrain only
has a base texture, and no layers).
This fixes the issue by adding a default texture to ADT chunk alpha
maps in the event no alpha maps were defined in the chunk's MCAL.
Closes #114.
> Fix: Added default texture to ADT chunk alpha maps

- src/lib/pipeline/adt/chunk/material.js
- src/lib/pipeline/m2/material/index.js
- src/lib/pipeline/m2/material/shader.vert
- src/lib/pipeline/texture-loader.js
- src/lib/pipeline/wmo/material/index.js
This fixes a few issues with how textures are handled in Wowser. See issue #106 for an example of what's fixed.
**M2Material should have flipY set to false on its textures**
```WMOMaterial``` disables ```flipY```, but ```M2Material``` doesn't disable it. Instead, ```M2Material``` is doing this in its shader:
```
texture1Coord = vec2(uv[0], -uv[1]);
texture2Coord = vec2(uv[0], -uv[1]);
```
This is fairly pointless, since just setting ```flipY``` to false a la ```WMOMaterial``` prevents the need to do the negation in the shader.
This is now fixed, and ```flipY``` is set to false for ```M2Material``` (matching ```WMOMaterial```).
**Textures should be cached and loaded based on texture settings**
Currently, the ```TextureLoader``` assumes that, for a given texture path, it will always be used …
> Fix: Texture settings

- src/lib/pipeline/m2/material/index.js
- src/lib/pipeline/m2/material/shader.frag
- src/lib/pipeline/wmo/material/shader.frag
This PR fixes various fog issues.
* Alpha transparencies in textures used in WMO materials flagged with opaque blending mode now get their alpha values forced to 1.0 prior to light and fog shading. This prevents oddities such as glowing stone textures on the Darkshire blacksmith chimney, various human stone towers, and so on. It also fixes the inappropriately bright textures in the Exodar (particularly noticeable in the entrance ramp to the Exodar).
* Similarly, M2 material textures that use alpha transparencies, but which render in the opaque blending mode, also get their alpha values forced to 1.0. This resolves overly bright textures in certain M2s, such as the burning ship at the entrance to Howling Fjord.
* All pixels now fully fade in to the fog. Perhaps because the actual game uses …
> Feature: Better fog

- src/lib/game/unit.js
- src/lib/game/world/doodad-manager.js
- src/lib/game/world/wmo-manager/wmo-handler.js
- src/lib/pipeline/m2/animation-manager.js
- src/lib/pipeline/m2/index.js
Additional groundwork for texture animations.
Please note that this PR includes commits from #126. We should ensure that PR is merged before tackling this PR.
Many (possibly even most) texture animations are part of global sequences rather than being set up as traditional animations. This PR adds support for global sequences to the M2 animation manager.
> Feature: M2 sequences

- src/lib/pipeline/m2/animation-manager.js
- src/lib/pipeline/m2/index.js
- src/lib/pipeline/m2/material/index.js
- src/lib/pipeline/m2/material/shader.frag
- src/lib/pipeline/m2/material/shader.vert
At long last: support for UV, transparency, and vertex color animations in M2Material.
Witness waterfalls, lavafalls, sandfalls, and more come to life before your very eyes.
This depends on PRs #126 and #127. This should close #96, #97, and #98.
Please note that UV animations currently only cover translations. I haven't yet found any models with UV animations for rotation or scaling.
> Feature: M2 texture animations

- package.json
- webpack.config.js
Several nice-to-haves as we continue to expand the shader logic present in Wowser:
* Added support for ```.glsl``` extensions
* Added support for passing transforms into glslify when loading source via ```glslify-loader```
* Added support for ```glslify-import```: we can now use statements like ```#pragma glslify: import('./common.glsl')``` in GLSL source to avoid code duplication
> Feature: glslify loader improvements

- src/lib/pipeline/m2/batch-manager.js
- src/lib/pipeline/m2/index.js
- src/lib/pipeline/m2/material/index.js
- src/lib/pipeline/m2/material/shader.frag
- src/lib/pipeline/m2/material/shader.vert
- src/lib/pipeline/m2/submesh.js
These changes are being done in preparation for the more significant changes relating to proper shaders for Wrath of the Lich King content.
* Renamed texture units to batches (a more conventional term, and one that matches debug strings in the client)
* Synced attribute name changes in parsed M2 and skin data against Blizzardry
* Migrated batch definition logic into a dedicated batch manager to reduce clutter in the root M2 class
* Switched to single transparency animation per batch based on observations from disassembly
> Feature: M2 batch cleanup

- src/lib/realms/handler.js
- src/lib/realms/realm.js
Not extracting this information will cause additional realms to be decoded incorrectly, potentially crashing and breaking the realm list in its entirety.
Works for a TrinityCore server, haven't tested this against ArcEmu yet.
> Extract realm build info when provided

- src/components/wowser/ui/frame/dividers/index.styl
This makes sure the yellow frame dividers actually show in Firefox – possibly other browsers, too.
**Before**
**After**
> Enforce border-style for dividers

- src/lib/server/pipeline/index.js
This filters away a bunch of internal properties from the pipeline results and adds a `link`-property.
Depending on the JSON viewing capabilities of the browser, it allows easy navigation between files in the game archives:
> Add links to pipeline results

- src/lib/server/pipeline/index.js
Express' `Response#type`-method will set the correct content type based on extension.
Among other things, this allows audio files to be played inline rather than prompting a download:
> Have Express set correct mime types

- README.md
@fallenoak uploaded a new tech demo quite a while ago. This PR updates the thumbnail and video reference in the README.
The new README can be previewed here: https://github.com/wowserhq/wowser/blob/37e91de1a3f7effa64d8ff6e9b90bcbfc1de62ba/README.md
> Reference second tech demo in README
